Repository RomainGuarinoni/mastermind, pull requests merged in 2022-02, with the labels that each got.

#14 BIG CHANGES : architecture
  .babelrc
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/combination.ts
  src/dom-manipulation.ts
  src/index.ts
  src/listeners.ts
  src/style/global.css
  tsconfig.json
  webpack.config.js
Labels: enhancement

#12 Add parameters to the game
  package-lock.json
  public/index.html
  public/pictures/parameterLogo.png
  src/combination.ts
  src/dom-manipulation.ts
  src/index.ts
  src/style/global.css
Labels: bug, enhancement

#22 Feat/test
  .github/workflows/test.yml
  .gitignore
  README.md
  jest.config.ts
  package-lock.json
  package.json
  test/combination.test.ts
  test/dom-manipulation.test.ts
Labels: enhancement

#33 feat(game): make targets zone wider
  src/combination.ts
  src/dom-manipulation.ts
  src/index.ts
  src/listeners.ts
  src/style/global.css
  test/combination.test.ts
  test/dom-manipulation.test.ts
Labels: enhancement

#35 Dynamic with of indicators containers
  src/dom-manipulation.ts
  src/index.ts
Labels: bug

#37 feat(style): update params style and global
  public/index.html
  src/style/global.css
Labels: enhancement

#40 feat(game): add tooltip to display rounds left
  public/index.html
  src/dom-manipulation.ts
  src/index.ts
  src/style/global.css
  test/dom-manipulation.test.ts
Labels: enhancement

#46 feat(docs): add jsdocs to the project
  jsdoc.json
  jsdocs/combination.ts.html
  jsdocs/dom-manipulation.ts.html
  jsdocs/global.html
  jsdocs/index.html
  jsdocs/index.ts.html
  jsdocs/listeners.ts.html
  jsdocs/scripts/app.min.js
  jsdocs/scripts/linenumber.js
  jsdocs/scripts/search.js
  jsdocs/styles/app.min.css
  jsdocs/styles/iframe.css
  jsdocs/styles/prettify-jsdoc.css
  jsdocs/styles/prettify-tomorrow.css
  jsdocs/styles/reset.css
  package-lock.json
  package.json
  src/combination.ts
  src/dom-manipulation.ts
  src/listeners.ts
Labels: documentation

#48 Feat/see game after end
  .prettierignore
  public/index.html
  src/dom-manipulation.ts
  src/index.ts
  src/listeners.ts
  src/style/global.css
  test/dom-manipulation.test.ts
Labels: enhancement
